name: Build and Versioning

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set package name and version
        id: set_name
        run: |
          echo "Checking GITHUB_REF: $GITHUB_REF"

          # Extract versioning info based on branch/tag
          if [[ "${{ inputs.branch }}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            PACKAGE_ID="nexus-git-${TAG_NAME}"
            PACKAGE_VERSION="${TAG_NAME}"
          else
            if [[ "${{ inputs.branch }}" == "refs/heads/development" ]]; then
              PACKAGE_ID="nexus-git-development"
              PACKAGE_VERSION="1.0.0-${{ github.run_id }}"
            elif [[ "${{ inputs.branch }}" == "refs/heads/release" ]]; then
              PACKAGE_ID="nexus-git-release"
              PACKAGE_VERSION="1.0.0-${{ github.sha }}"
            else
              PACKAGE_ID="nexus-git-master"
              PACKAGE_VERSION="1.0.1"
            fi
          fi

          # Set outputs for use in the main workflow
          echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          
          echo "::set-output name=package_id::${PACKAGE_ID}"
          echo "::set-output name=package_version::${PACKAGE_VERSION}"
