name: Build and Publish

on:
  push:
    branches:
      - development
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify the .NET version you want to use

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./output

    - name: Determine Package Name
      id: package_name
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
          echo "PACKAGE_NAME=nexus-git-${GITHUB_HEAD_REF}-1.0.0" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
          echo "PACKAGE_NAME=release-1.0.1-${GITHUB_SHA}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
          echo "PACKAGE_NAME=release-1.0.1-${GITHUB_SHA}" >> $GITHUB_ENV
          echo "TAG_NAME=1.0.1" >> $GITHUB_ENV
        fi

    - name: Publish to Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/development" || "${GITHUB_REF}" == "refs/heads/release" ]]; then
          dotnet nuget push ./output/${{ env.PACKAGE_NAME }}.nupkg --source http://52.187.94.85:8081/repository/yashm-nuget/ --api-key ${{ secrets.NEXUS_API_KEY }}
        fi

    - name: Create Tag for Master Branch
      if: github.ref == 'refs/heads/master'
      run: |
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}