name: Build and Publish

on:
  push:
    branches:
      - development
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify the .NET version you want to use

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./output

    - name: Pack
      id: pack
      run: |
        # Get the short commit ID (first 6 characters of the commit hash)
        SHORT_COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)

        # Determine the package name based on the branch
        if [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
          # For development branch, include job ID in the package name
          PACKAGE_NAME="nexus-git_${GITHUB_RUN_ID}_develop.nupkg"
        elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
          # For release branch, use version 1.0.0 and include short commit ID
          PACKAGE_NAME="nexus-git_1.0.0_release_${SHORT_COMMIT_ID}.nupkg"
        fi

        # Use dotnet pack with a dynamically set version and output filename
        dotnet pack --configuration Release --output ./output --no-build \
          /p:PackageVersion=1.0.0 \
          /p:PackageId="nexus-git" \
          /p:FileVersion="${SHORT_COMMIT_ID}" \
          /p:PackageReleaseNotes="Built from ${GITHUB_REF} branch at commit ${GITHUB_SHA}"

        # List files in the output directory to see the exact generated package name
        echo "Listing files in output directory:"
        ls -la ./output

        # Rename the generated .nupkg file to match the desired format
        GENERATED_PACKAGE=$(ls ./output/*.nupkg)
        mv "$GENERATED_PACKAGE" "./output/${PACKAGE_NAME}"
        echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV

    - name: List output directory
      run: ls -la ./output

    - name: Publish to Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
      run: |
        echo "Pushing package: ./output/${{ env.PACKAGE_NAME }}"

        # Ensure we're pushing from development or release branch with correct file name
        if [[ "${GITHUB_REF}" == "refs/heads/development" || "${GITHUB_REF}" == "refs/heads/release" ]]; then
          # Push the package to Nexus with the correct naming convention
          dotnet nuget push "./output/${{ env.PACKAGE_NAME }}" --source http://52.187.94.85:8081/repository/yashm-nuget/ --api-key ${{ secrets.NEXUS_API_KEY }} 
        fi

  tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get release version from release branch
      run: |
        # You can extract this dynamically from tags or files if needed
        VERSION="1.0.0"  
        PACKAGE_NAME="nexus-git-${VERSION}.nupkg"
        echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV

    - name: Create Tag
      run: |
        # Create a new tag for version 1.0.0 on master
        git tag -a "v1.0.0" -m "Release version 1.0.0"
        git push origin v1.0.0

    - name: List output directory (Master)
      run: ls -la ./output

    - name: Publish to Nexus (Master)
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
      run: |
        echo "Pushing package: ./output/${{ env.PACKAGE_NAME }}"
        # Publish the package to Nexus with the version from the release branch
        dotnet nuget push "./output/${{ env.PACKAGE_NAME }}" --source http://52.187.94.85:8081/repository/yashm-nuget/ --api-key ${{ secrets.NEXUS_API_KEY }} 
