name: Publish Package

on:
  push:
    branches:
      - master
      - development
      - release
    tags:
      - '*'

env:
  PACKAGE_ID: ""
  PACKAGE_VERSION: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Build Project 
        uses: ./.github/actions/build  

      - name: Set package name and version
        id: set_name
        run: |
          echo "Checking GITHUB_REF: $GITHUB_REF"
          FOLDER_NAME="nexus-git-development"

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"

            git fetch origin master
            MASTER_COMMIT=$(git rev-parse origin/master)

            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")

            if [[ "$TAG_COMMIT" == "$MASTER_COMMIT" ]]; then
              export PACKAGE_ID="nexus-git-${TAG_NAME}"
              export PACKAGE_VERSION="${TAG_NAME}"
            else
              echo "Error: Tags must be created on the master branch."
              exit 1
            fi
          elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
            export PACKAGE_ID="${FOLDER_NAME}.nexus-git"
            export PACKAGE_VERSION="1.0.0-${GITHUB_RUN_ID}"
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)
            export PACKAGE_ID="nexus-git-1.0.0-release-${COMMIT_ID}"
            export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
          elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            echo "Advised to provide tag with the master branch, can't proceed further."
            exit 1
          fi 

          echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

          echo "PACKAGE_ID: $PACKAGE_ID"
          echo "PACKAGE_VERSION: $PACKAGE_VERSION"

      - name: Pack project
        run: |
          echo "Packaging with version: $PACKAGE_VERSION"
          dotnet pack --configuration Release --output ./bin/Release \
            /p:CustomPackageId=$PACKAGE_ID \
            /p:PackageVersion=$PACKAGE_VERSION

      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./bin/Release/$PACKAGE_ID.$PACKAGE_VERSION.nupkg

  sonar_scan:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Run SonarQube Analysis
        uses: ./.github/actions/sonar-scan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate (Master Branch with Tag Only)
        if: github.ref == 'refs/heads/master' && startsWith(env.GITHUB_REF, 'refs/tags/')
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Checking Quality Gate for Master branch with a tag."
          QUALITY_GATE_STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=yashmahi88_nexus-git" \
            | jq -r '.projectStatus.status')

          echo "Quality Gate Status: $QUALITY_GATE_STATUS"

          if [[ "$QUALITY_GATE_STATUS" != "OK" ]]; then
            echo "Quality Gate failed. Exiting..."
            exit 1
          fi

      - name: Skip Quality Gate Check (Master Without Tag)
        if: github.ref == 'refs/heads/master' && !startsWith(env.GITHUB_REF, 'refs/tags/')
        run: |
          echo "Master branch detected but no valid tag provided. Skipping Quality Gate check."

  push_to_nexus:
    runs-on: ubuntu-latest
    needs: sonar_scan
    environment: nexus-approval
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget-package
          path: ./bin/Release

      - name: List files in Release directory
        run: ls -al ./bin/Release
  
      - name: Push to Nexus Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        run: |
          dotnet nuget push ./bin/Release/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg \
            --source http://52.187.94.85:8081/repository/nuget-rc \
            --api-key $NEXUS_API_KEY
