name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./output

    - name: Install NuGet CLI
      run: |
        wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        sudo mv nuget.exe /usr/local/bin/nuget

    - name: Publish to Nexus using NuGet CLI
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        # Push the .nupkg package to Nexus
        nuget push ./bin/Release/nexus-git.1.0.0.nupkg -Source http://52.187.94.85:8081/repository/yashm-nuget/ -ApiKey $NEXUS_PASSWORD
