name: Publish Package

on:
  push:
    branches:
      - develop
      - release
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify the version of .NET you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Set package name
        id: set_name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            PACKAGE_ID="nexus-git-${{ github.run_id }}-develop"
          elif [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-6)
            PACKAGE_ID="nexus-git-1.0.0-release-${COMMIT_ID}"
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            PACKAGE_ID="nexus-git-1.0.0"
          fi
          echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV

      - name: Pack project
        run: dotnet pack --configuration Release --output ./bin/Release /p:CustomPackageId=${{ env.PACKAGE_ID }}

      - name: Push to Nexus Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        run: |
          dotnet nuget push ./bin/Release/${{ env.PACKAGE_ID }}.1.0.0.nupkg --source http://52.187.94.85:8081/repository/yashm-nuget/ --api-key $NEXUS_API_KEY  
          