name: Publish Package

on:
  push:
    branches:
      - master
      - development
      - release
    tags:
      - '*'  

jobs:
  build:
    uses: ./.github/workflows/build.yaml  
    with:
      branch: ${{ github.ref }}  

  pack:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Pack project
        run: |
          echo "Packaging with version: ${{ needs.build.outputs.package_version }}"
          dotnet pack ./nexus-git.csproj --configuration Release --output ./bin/Release \
            /p:CustomPackageId=${{ needs.build.outputs.package_id }} \
            /p:PackageVersion=${{ needs.build.outputs.package_version }}
          
          ls -al ./bin/Release
      

      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./bin/Release/${{ needs.build.outputs.package_id }}.${{ needs.build.outputs.package_version }}.nupkg

  push_to_nexus:
    runs-on: ubuntu-latest
    needs: pack  
    environment: nexus-approval

    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget-package
          path: ./bin/Release

      - name: List files in Release directory
        run: ls -al ./bin/Release

      - name: Push to Nexus Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        run: |
          dotnet nuget push ./bin/Release/${{ needs.pack.outputs.package_id }}.${{ needs.pack.outputs.package_version }}.nupkg --source http://52.187.94.85:8081/repository/nuget-tag/ --api-key $NEXUS_API_KEY
