name: Main Workflow

on:
  push:
    branches:
      - development
      - release
    tags:
      - '*'

jobs:
  call_publish_package:
    uses: yashmahi88/.github/.github/workflows/publish-package.yml@main
    # with:
    #   project_key: ${{ vars.PROJECT_KEY }}
    #   project_name: ${{ vars.PROJECT_NAME }}
    # secrets: inherit

  call_sonar_scan:
    needs: call_publish_package 
    uses: yashmahi88/.github/.github/workflows/sonar-scan.yml@main
    with:
      project_key: ${{ vars.PROJECT_KEY }}
      project_name: ${{ vars.PROJECT_NAME }}
    secrets: inherit
 