name: Call Publish Package Workflow

on:
  push:
    branches:
      - development
      - release
    tags:
      - '*'

jobs:
  call_publish_package:
    uses: yashmahi88/.github/workflow-templates/publish-package.yml@main
    with:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}
      nexus_api_key: ${{ secrets.NEXUS_API_KEY }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}